dataset:
  target: dataset.motionbrain_revised.MotionbrainDataset_2
  params:
    # Path to the file list.
    file_list: data/train_hcp.list
    out_size: 512
    crop_type: center
    # use_hflip: False

data_loader:
  batch_size: 40 
  shuffle: true
  num_workers: 4
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
