dataset:
  target: dataset.motionbrain_revised.MotionbrainDataset_2
  params:
    # Path to the file list.
    file_list: data/val_hcp.list
    out_size: 512 
    crop_type: center #none
    # use_hflip: False

data_loader:
  batch_size: 20 
  shuffle: false 
  num_workers: 0
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
