data:
  target: dataset.data_module.BIRDataModule
  params:
    # Path to training set configuration file.
    train_config: /public_bme/data/lifeng/code/moco/TS_BHIR/configs/dataset/brainT1_train.yaml
    # Path to validation set configuration file.
    val_config: /public_bme/data/lifeng/code/moco/TS_BHIR/configs/dataset/brainT1_val.yaml

model:
  # You can set learning rate in the following configuration file.
  config: /public_bme/data/lifeng/code/moco/TS_BHIR/configs/model/swinir.yaml
  # Path to the checkpoints or weights you want to resume.
  resume: /public_bme2/bme-wangqian2/lifeng2023/data/mic_extension/swinir_512_axis/dbt_plus_checkpoints/lightning_logs/version_2978852/checkpoints/step=249.ckpt


lightning:
  seed: 231
  
  trainer:
    accelerator: ddp
    precision: 32
    # Indices of GPUs used for training.
    gpus: [0]
    # Path to save logs and checkpoints.
    default_root_dir: /public_bme2/bme-wangqian2/lifeng2023/data/mic_extension/swinir_512_axis/dbt_plus_gate1_checkpoints_revise
    #/public_bme2/bme-wangqian2/lifeng2023/data/mic_extension/swinir_512_axis/dbt_checkpoints
    # Max number of training steps (batches).
    max_steps: 150001
    # Validation frequency in terms of training steps.
    val_check_interval: 12.0 
    # Log frequency of tensorboard logger.
    log_every_n_steps: 30 
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 10 
        max_images_each_step: 1 
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 30 
        save_top_k: -1
        filename: "{step}"
